# Generated by Django 3.2.25 on 2024-12-22 13:10

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google', models.CharField(default='', max_length=100)),
                ('Facebook', models.CharField(default='', max_length=100)),
                ('Supercell', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('Lvl', models.IntegerField(default=1)),
                ('village', models.FileField(max_length=100000, upload_to=account.models.uploadfile)),
                ('dark_village', models.FileField(blank=True, max_length=100000, null=True, upload_to=account.models.uploadfile)),
                ('SeassonProgress', models.FileField(blank=True, max_length=100000, null=True, upload_to=account.models.uploadfile)),
                ('eventProgress', models.FileField(blank=True, max_length=100000, null=True, upload_to=account.models.uploadfile)),
                ('starRewards', models.CharField(choices=[('no_stars', 'no_stars'), ('one_star', 'one_star'), ('tow_stars', 'tow_stars'), ('complete', 'complete')], default='no_stars', max_length=50)),
                ('league_cup', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('join_at', models.DateTimeField()),
                ('achivement', models.FileField(upload_to=account.models.uploadfile)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.linkway')),
            ],
        ),
    ]
