# Generated by Django 3.2.25 on 2024-12-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
